"""PRINet: Polyadic Resonance Inference Network.

A novel AI architecture based on resonance dynamics, polyadic tensor
decomposition, and phase synchronization. PRINet processes information
via multi-dimensional harmonic resonances rather than token embeddings.

Packages:
    core: Fundamental dynamics (decomposition, propagation, measurement).
    nn: PyTorch-compatible layers and optimizers.
    utils: GPU-accelerated solvers and utilities.

Example:
    >>> import torch
    >>> from prinet.nn import PRINetModel
    >>> model = PRINetModel(n_resonances=64, n_dims=256, n_concepts=10)
    >>> x = torch.randn(32, 256)
    >>> log_probs = model(x)
    >>> print(log_probs.shape)
    torch.Size([32, 10])
"""

__version__ = "3.0.0"
__author__ = "Michael Maillet, Damien Davison, Sacha Davison"

from prinet.core import (
    CONTROL_DIM,
    STATE_DIM,
    ControlSignalBuffer,
    ControlSignals,
    CPDecomposition,
    DeltaThetaGammaNetwork,
    DentateGyrusConverter,
    DiscreteDeltaThetaGamma,
    ExponentialIntegrator,
    FeedbackInhibition,
    FeedforwardInhibition,
    HopfOscillator,
    KuramotoOscillator,
    MultiRateIntegrator,
    OscillatorModel,
    OscillatorState,
    PhaseAmplitudeCoupling,
    PolyadicTensor,
    StuartLandauOscillator,
    SubconsciousDaemon,
    SubconsciousState,
    TemporalPhasePropagator,
    ThetaGammaNetwork,
    build_phase_knn,
    collect_system_state,
    detect_oscillation,
    inter_frame_phase_correlation,
    kuramoto_order_parameter,
    mean_phase_coherence,
    phase_coherence_matrix,
    phase_to_rate,
    sparse_mean_phase_coherence,
    sparse_synchronization_energy,
    sweep_coupling_params,
)
from prinet.nn import retrain_controller  # Y2 Q3: Architecture v2, MOT, telemetry
from prinet.nn import (  # Q4: Hybrid architecture; Y2 Q1: Discrete multi-rate & oscillatory attention; Y2 Q2: Temporal & active control; Y3 Q4: Slot Attention comparison (P.5); Y4 Q1: Temporal Slot Attention MOT (T.3); Y4 Q1.7: Ablation variants
    ActiveControlTrainer,
    AlternatingOptimizer,
    DenseAutoencoder,
    DGLayer,
    DiscreteDeltaThetaGammaLayer,
    GatedPhaseActivation,
    HierarchicalResonanceLayer,
    HolomorphicActivation,
    HolomorphicEnergy,
    HolomorphicEPTrainer,
    HybridCLEVRN,
    HybridPRINet,
    HybridPRINetV2,
    HybridPRINetV2CLEVRN,
    InterleavedHybridPRINet,
    OscillatoryAttention,
    PhaseActivation,
    PhaseAmplitudeCouplingLayer,
    PhaseToRateAutoencoder,
    PhaseToRateConverter,
    PhaseTracker,
    PhaseTrackerFrozen,
    PhaseTrackerStatic,
    PRINetModel,
    ResonanceLayer,
    RIPOptimizer,
    SCALROptimizer,
    SlotAttentionCLEVRN,
    SlotAttentionFrozen,
    SlotAttentionModule,
    SlotAttentionNoGRU,
    SparsityRegularizationLoss,
    StateCollector,
    SubconsciousController,
    SynchronizedGradientDescent,
    TelemetryLogger,
    TemporalHybridPRINet,
    TemporalSlotAttentionMOT,
    compile_model,
    create_ablation_tracker,
    dSiLU,
    oscillatory_weight_init,
)
from prinet.utils import (
    AblationConfig,
    AblationHybridPRINetV2,
    AsyncCPUGPUPipeline,
    BackendType,
    BatchedRK45Solver,
    ExtendedTrainingResult,
    FixedStepRK4Solver,
    LargeScaleOscillatorSystem,
    MixedPrecisionTrainer,
    MultiSeedResult,
    OscillatorPruner,
    OscilloSim,
    SequenceData,
    SimulationResult,
    SolverResult,
    TemporalMetrics,
    TemporalTrainer,
    TrainingResult,
    TrainingSnapshot,
    backend_info,
    bimodality_index,
    binding_robustness_score,
    build_knn_neighbors,
    compute_full_temporal_metrics,
    compute_p_value,
    count_flops,
    count_parameters,
    create_ablation_model,
    create_session,
    csr_coupling_step,
    cuda_fused_kernel_available,
    detect_best_backend,
    directml_available,
    fused_discrete_step_cuda,
    generate_benchmark_report,
    generate_dataset,
    generate_leaderboard,
    generate_scalr_metrics_report,
    generate_temporal_clevr_n,
    gradient_checkpoint_integration,
    hungarian_similarity_loss,
    identity_overcount,
    identity_switches,
    local_order_parameter,
    measure_wall_time,
    mostly_tracked_lost,
    npu_available,
    pytorch_cross_band_coupling,
    pytorch_fused_discrete_step,
    pytorch_fused_discrete_step_full,
    pytorch_fused_sub_step_rk4,
    pytorch_hierarchical_order_param,
    pytorch_mean_field_rk4_step,
    pytorch_multi_rate_derivatives,
    pytorch_multi_rate_rk4_step,
    pytorch_pac_modulation,
    pytorch_sparse_knn_coupling,
    quick_simulate,
)
from prinet.utils import (
    recovery_speed as temporal_recovery_speed,  # Y4 Q1.7: Temporal metrics; Y4 Q1.7: Temporal training
)
from prinet.utils import (
    ring_topology,
    small_world_topology,
    sparse_coupling_matrix,
    sparse_coupling_matrix_csr,
    sparse_knn_coupling_step,
    temporal_smoothness,
    temporal_smoothness_loss,
    track_duration_stats,
    track_fragmentation_rate,
    train_clevr_n_extended,
    train_clevr_n_single_seed,
    train_multi_seed,
    triton_available,
    triton_fused_discrete_step,
    triton_fused_mean_field_rk4_step,
    triton_hierarchical_order_param,
    triton_pac_modulation,
    triton_sparse_knn_coupling,
)

# Y4 Q2: Publication figure/table generation
from prinet.utils.figure_generation import (
    configure_neurips_style,
    fig_ablation_results,
    fig_chimera_heatmap,
    fig_clevr_n_capacity,
    fig_gold_standard_chimera,
    fig_mot_identity_preservation,
    fig_oscillosim_scaling,
    fig_parameter_efficiency,
    fig_statistical_summary,
    fig_training_curves,
    generate_all_figures,
)
from prinet.utils.table_generation import (
    generate_all_tables,
    table_ablation_variants,
    table_chimera_gold_standard,
    table_occlusion_sweep,
    table_oscillosim_scaling,
    table_parameter_efficiency,
    table_statistical_summary,
)

__all__ = [
    # Core
    "PolyadicTensor",
    "CPDecomposition",
    "OscillatorModel",
    "OscillatorState",
    "KuramotoOscillator",
    "StuartLandauOscillator",
    "HopfOscillator",
    "ExponentialIntegrator",
    "kuramoto_order_parameter",
    "mean_phase_coherence",
    "phase_coherence_matrix",
    "build_phase_knn",
    "sparse_mean_phase_coherence",
    "sparse_synchronization_energy",
    # Core — Q3 Hierarchical
    "DeltaThetaGammaNetwork",
    "ThetaGammaNetwork",
    "PhaseAmplitudeCoupling",
    "MultiRateIntegrator",
    "detect_oscillation",
    "phase_to_rate",
    "sweep_coupling_params",
    # Core — Q3 Inhibition & DG
    "FeedforwardInhibition",
    "FeedbackInhibition",
    "DentateGyrusConverter",
    # Neural Network
    "ResonanceLayer",
    "PRINetModel",
    "compile_model",
    "oscillatory_weight_init",
    "SynchronizedGradientDescent",
    "SCALROptimizer",
    "RIPOptimizer",
    "HolomorphicEnergy",
    "HolomorphicEPTrainer",
    "dSiLU",
    "HolomorphicActivation",
    "PhaseActivation",
    # Neural Network — Q3
    "GatedPhaseActivation",
    "PhaseToRateConverter",
    "SparsityRegularizationLoss",
    "HierarchicalResonanceLayer",
    "PhaseAmplitudeCouplingLayer",
    # Neural Network — Q3 late
    "DGLayer",
    "PhaseToRateAutoencoder",
    "DenseAutoencoder",
    # Utils
    "BatchedRK45Solver",
    "FixedStepRK4Solver",
    "SolverResult",
    "sparse_coupling_matrix",
    "gradient_checkpoint_integration",
    # Triton Kernels (Q2)
    "triton_available",
    "triton_fused_mean_field_rk4_step",
    "triton_sparse_knn_coupling",
    "pytorch_mean_field_rk4_step",
    "pytorch_sparse_knn_coupling",
    # Triton Kernels (Q3)
    "triton_pac_modulation",
    "triton_hierarchical_order_param",
    "pytorch_pac_modulation",
    "pytorch_hierarchical_order_param",
    "pytorch_multi_rate_rk4_step",
    # Triton Kernels (Q3 late — multi-rate)
    "pytorch_multi_rate_derivatives",
    "pytorch_fused_sub_step_rk4",
    "pytorch_cross_band_coupling",
    # Benchmark reporting (Q3)
    "generate_benchmark_report",
    "generate_leaderboard",
    "generate_scalr_metrics_report",
    # Q4: Subconscious layer
    "SubconsciousState",
    "ControlSignals",
    "ControlSignalBuffer",
    "STATE_DIM",
    "CONTROL_DIM",
    "SubconsciousDaemon",
    "collect_system_state",
    "SubconsciousController",
    # Q4: NPU backend
    "BackendType",
    "detect_best_backend",
    "npu_available",
    "directml_available",
    "create_session",
    "backend_info",
    # Q4: Hybrid architecture
    "HybridPRINet",
    "HybridCLEVRN",
    "AlternatingOptimizer",
    "StateCollector",
    # Y2 Q1: Discrete multi-rate, oscillatory attention, interleaved hybrid
    "DiscreteDeltaThetaGamma",
    "DiscreteDeltaThetaGammaLayer",
    "OscillatoryAttention",
    "InterleavedHybridPRINet",
    # Y2 Q2: Temporal binding & active control
    "TemporalPhasePropagator",
    "inter_frame_phase_correlation",
    "TemporalHybridPRINet",
    "ActiveControlTrainer",
    "retrain_controller",
    # Y2 Q3: Architecture v2, MOT, fused kernels
    "HybridPRINetV2",
    "HybridPRINetV2CLEVRN",
    "PhaseTracker",
    "TelemetryLogger",
    "triton_fused_discrete_step",
    "pytorch_fused_discrete_step",
    # Y3 Q3: CUDA C++ fused kernels (O.2)
    "cuda_fused_kernel_available",
    "fused_discrete_step_cuda",
    "pytorch_fused_discrete_step_full",
    # Y3 Q3: Mixed-precision training (O.3)
    "MixedPrecisionTrainer",
    # Y3 Q3: CSR sparse coupling (R.4)
    "sparse_coupling_matrix_csr",
    "csr_coupling_step",
    # Y3 Q3: Large-scale oscillators (O.4)
    "LargeScaleOscillatorSystem",
    "build_knn_neighbors",
    "sparse_knn_coupling_step",
    # Y3 Q3: Async CPU+GPU pipeline (O.5)
    "AsyncCPUGPUPipeline",
    # Y3 Q3: Model pruning (O.6)
    "OscillatorPruner",
    # Y3 Q4: OscilloSim v2.0 (P.4)
    "OscilloSim",
    "SimulationResult",
    "quick_simulate",
    # Y3 Q4: Slot Attention comparison (P.5)
    "SlotAttentionModule",
    "SlotAttentionCLEVRN",
    # Y4 Q1: Temporal Slot Attention MOT (T.3)
    "TemporalSlotAttentionMOT",
    # Y4 Q1: Ring/small-world topologies & chimera detection (T.1, T.2)
    "ring_topology",
    "small_world_topology",
    "local_order_parameter",
    "bimodality_index",
    # Y4 Q1: Ablation, extended training, FLOPs (T.4, T.5, T.6)
    "AblationConfig",
    "AblationHybridPRINetV2",
    "create_ablation_model",
    "ExtendedTrainingResult",
    "train_clevr_n_single_seed",
    "train_clevr_n_extended",
    "compute_p_value",
    "count_flops",
    "measure_wall_time",
    # Y4 Q1.7: Ablation variants
    "PhaseTrackerFrozen",
    "PhaseTrackerStatic",
    "SlotAttentionNoGRU",
    "SlotAttentionFrozen",
    "create_ablation_tracker",
    # Y4 Q1.7: Temporal metrics
    "TemporalMetrics",
    "temporal_smoothness",
    "identity_switches",
    "track_fragmentation_rate",
    "identity_overcount",
    "mostly_tracked_lost",
    "track_duration_stats",
    "temporal_recovery_speed",
    "binding_robustness_score",
    "compute_full_temporal_metrics",
    # Y4 Q1.7: Temporal training
    "SequenceData",
    "generate_temporal_clevr_n",
    "generate_dataset",
    "hungarian_similarity_loss",
    "temporal_smoothness_loss",
    "count_parameters",
    "TrainingSnapshot",
    "TrainingResult",
    "TemporalTrainer",
    "MultiSeedResult",
    "train_multi_seed",
    # Y4 Q2: Publication figure generation
    "configure_neurips_style",
    "fig_clevr_n_capacity",
    "fig_chimera_heatmap",
    "fig_mot_identity_preservation",
    "fig_oscillosim_scaling",
    "fig_ablation_results",
    "fig_parameter_efficiency",
    "fig_training_curves",
    "fig_gold_standard_chimera",
    "fig_statistical_summary",
    "generate_all_figures",
    # Y4 Q2: Publication table generation
    "table_ablation_variants",
    "table_parameter_efficiency",
    "table_chimera_gold_standard",
    "table_statistical_summary",
    "table_occlusion_sweep",
    "table_oscillosim_scaling",
    "generate_all_tables",
]
